Let us create an np vector as:
x = np.array ([[1,2,3,4,5,6],[7,8,9,10,11,12]])

And then we do following x[1,::2].

What is that :: operator doing?

What would it output?

Answers:

[10,11,12]. It subsets for the 1th x dimension, then gives everything after the 2nd indexed element in the 1th vector. 

[7,9,11]. It subsets for the 1th x dim, then produces EVERY OTHER value in that vectors elements. 
  
[7,8,9]. It subsets for the 1th x dim, then produces everything UP TO the 2nd element indexed in the vector.

In [1]:
import numpy as np

In [16]:
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
x #Display the 2 dimensional array x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
x[1] #subsets for the second element in the array (index 1)

array([ 7,  8,  9, 10, 11, 12])

In [12]:
x[1,::2] #[start:end:step] Start at beginning, end at end, select every second element

array([ 7,  9, 11])